all: revision sgoinstall

revision:
	@echo '// Autogenerated. Do not edit!' > sgo/revision.go
	@echo '' >> sgo/revision.go
	@echo 'package sgo' >> sgo/revision.go
	@echo '' >> sgo/revision.go
	@echo "var SGoRevision = \"`git log | head -n 1 | cut -d ' ' -f 2`\"" >> sgo/revision.go

sgoinstall:
	sgo install ./...
